name: GithHub Action CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: GitOps Workflow
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build an image from Dockerile
              run: |
                DOCKER_BUILDKIT=1 docker image build apps/ -t ghcr.io/qian-github-cloud/${{github.repository}}/go-image:${{github.run_number}}

            - name: GitHub Packages Login
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{secrets.USERNAME}}
                password: ${{secrets.PERSONAL_ACCESS_TOKEN}}

            - name: Push image to GitHub
              run: docker image push ghcr.io/qian-github-cloud/${{github.repository}}/go-image:${{github.run_number}} 