name: GithHub Action CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: GitOps Workflow
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2


            - name: Application test
              run: |
               cd apps
               make run-test

            - name: Build an image from Dockerile
              run: |
                DOCKER_BUILDKIT=1 docker image build apps/ -t ghcr.io/${{github.repository}}/go-image:${{github.run_number}}

            - name: Run dockle
              uses: hands-lab/dockle-action@v1
              with:
                image: ghcr.io/${{github.repository}}/go-image:${{github.run_number}}

            - name: Run Trivy
              uses: aquasecurity/trivy-action@master
              with:
                image: ghcr.io/${{github.repository}}/go-image:${{github.run_number}}
                format: 'table'
                exit-code: '1'
                ignore-unfixed: 'true'
                severity: 'CRITICAL,HIGH'

            - name: GitHub Packages Login
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{secrets.USERNAME}}
                password: ${{secrets.PERSONAL_ACCESS_TOKEN}}

            - name: Push image to GitHub
              run: docker image push ghcr.io/${{github.repository}}/go-image:${{github.run_number}} 
    create-pr-k8s-manifest:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
            repository: qian-github-cloud/cicd-handson-2021-config
        - name: Pull Request to Config Repository
          run: |
            echo -e "machine github.com\nlogin ${{secrets.USERNAME}}\npassword ${{secrets.PERSONAL_ACCESS_TOKEN}}" > ~/.netrc
            git config --global user.name "{{secrets.USERNAME}}"
            git config --global user.email "{{secrets.EMAIL}}"

            git branch feature/${{github.run_number}}
            git checkout feature/${{github.run_number}}

            sed -i -e "s|image: ghcr.io/${{github.repository}}/go-image:.*|image: ghcr.io/${{github.repository}}/go-image:${{github.run_number}}|" manifests/goapp.yaml

            git add manifests
            git commit -m "Update tag ${{github.run_number}}"
            git push origin feature/${{github.run_number}}

            echo ${{secret.PERSONAL_ACCESS_TOKEN}} > token.txt
            gh auth login --with-token < token.txt
            gh pr create --title "Update Tag ${{github.run_number}}" --body "Please Merge !!"