name: GithHub Action CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: GitOps Workflow
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2


            - name: Application test
              run: |
               cd apps
               make run-test

            - name: Build an image from Dockerile
              run: |
                DOCKER_BUILDKIT=1 docker image build apps/ -t ghcr.io/${{github.repository}}/go-image:${{github.run_number}}

            - name: Run dockle
              uses: hands-lab/dockle-action@v1
              with:
                image: ghcr.io/${{github.repository}}/go-image:${{github.run_number}}

            - name: Run Trivy
              uses: aquasecurity/trivy-action@master
              with:
                image: ghcr.io/${{github.repository}}/go-image:${{github.run_number}}
                format: 'table'
                exit-code: '1'
                ignore-unfixed: 'true'
                severity: 'CRITICAL,HIGH'

            - name: GitHub Packages Login
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{secrets.USERNAME}}
                password: ${{secrets.PERSONAL_ACCESS_TOKEN}}

            - name: Push image to GitHub
              run: docker image push ghcr.io/${{github.repository}}/go-image:${{github.run_number}} 